# Generated by Django 4.0.3 on 2022-04-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_poo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poo',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
    ]
